name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '5 5 * * *'

jobs:
  in_docker_compose:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run docker-compose as a daemon
      run: docker-compose up -d

    - name: List docker containers
      run: docker ps -a

    - name: Ping the services to show network connectivity
      run: |
        docker exec github-actions-docker-compose_web_1 ping -c 1 mymongo

    - name: Run Tests
      run: |
        docker exec github-actions-docker-compose_web_1 pytest -svv

    - name: Stop the docker compose
      run: docker-compose stop -t 0
